package org.srcm.pmp.domain;
// Generated 28 Sep, 2015 3:44:34 AM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "program")
public class Program implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int programId;
	private String programChannel;
	private Date programDate;
	private String coordName;
	private String coordEmail;
	private String coordCenterName;
	private String coordState;
	private String coordCountry;
	private String instName;
	private String instWebsite;
	private Date programStartDate;
	private String programRawDate;
	private Date createTime;
	private Date updateTime;
	private String createdBy;
	private String updatedBy;
	private List<SeekerAims> seekerAimses = new ArrayList<SeekerAims>();

	public Program() {
	}

	public Program(int programId) {
		this.programId = programId;
	}

	public Program(String programChannel, String coordName, String coordEmail,
			String coordCenterName, String coordCountry, String instName, String instWebsite, Date programStartDate,
			String programRawDate,String coordState,
			List<SeekerAims> seekerAimses) {
		this.programChannel = programChannel;
		this.coordName = coordName;
		this.coordEmail = coordEmail;
		this.coordCenterName = coordCenterName;
		this.coordCountry = coordCountry;
		this.instName = instName;
		this.instWebsite = instWebsite;
		this.programStartDate = programStartDate;
		this.programRawDate = programRawDate;
		this.seekerAimses = seekerAimses;
		this.coordState = coordState;
	}

	
	@Id
	@GenericGenerator(name="pinc" , strategy="increment")
	@GeneratedValue(generator="pinc")
	@Column(name = "Program_id")
	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	@Column(name = "Program_channel")
	public String getProgramChannel() {
		return this.programChannel;
	}

	public void setProgramChannel(String programChannel) {
		this.programChannel = programChannel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Program_date")
	public Date getProgramDate() {
		return this.programDate;
	}

	public void setProgramDate(Date programDate) {
		this.programDate = programDate;
	}

	@Column(name = "Coord_Name")
	public String getCoordName() {
		return this.coordName;
	}

	public void setCoordName(String coordName) {
		this.coordName = coordName;
	}

	@Column(name = "Coord_Email")
	public String getCoordEmail() {
		return this.coordEmail;
	}

	public void setCoordEmail(String coordEmail) {
		this.coordEmail = coordEmail;
	}

	@Column(name = "Coord_Center_Name")
	public String getCoordCenterName() {
		return this.coordCenterName;
	}

	public void setCoordCenterName(String coordCenterName) {
		this.coordCenterName = coordCenterName;
	}

	/**
	 * @return the coordState
	 */
	@Column(name = "Coord_State")
	public String getCoordState() {
		return coordState;
	}

	/**
	 * @param coordState the coordState to set
	 */
	public void setCoordState(String coordState) {
		this.coordState = coordState;
	}

	@Column(name = "Coord_Country")
	public String getCoordCountry() {
		return this.coordCountry;
	}

	public void setCoordCountry(String coordCountry) {
		this.coordCountry = coordCountry;
	}

	@Column(name = "Inst_Name")
	public String getInstName() {
		return this.instName;
	}

	public void setInstName(String instName) {
		this.instName = instName;
	}

	@Column(name = "Inst_Website")
	public String getInstWebsite() {
		return this.instWebsite;
	}

	public void setInstWebsite(String instWebsite) {
		this.instWebsite = instWebsite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Program_Start_Date")
	public Date getProgramStartDate() {
		return this.programStartDate;
	}

	public void setProgramStartDate(Date programStartDate) {
		this.programStartDate = programStartDate;
	}

	@Column(name = "Program_raw_Date")
	public String getProgramRawDate() {
		return this.programRawDate;
	}

	public void setProgramRawDate(String programRawDate) {
		this.programRawDate = programRawDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time")
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "Created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "program")
	public List<SeekerAims> getSeekerAimses() {
		return this.seekerAimses;
	}

	public void setSeekerAimses(List<SeekerAims> seekerAimses) {
		this.seekerAimses = seekerAimses;
	}

}
