package org.srcm.pmp.domain;
// Generated 28 Sep, 2015 3:44:34 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * SeekerAims generated by hbm2java
 */
@Entity
@Table(name = "seeker_aims")
public class SeekerAims implements java.io.Serializable {

	private int seekerId;
	private Program program;
	private String firstName;
	private String lastName;
	private String middleName;
	private String email;
	private String phoneMobile;
	private Integer gender;
	private Date dateOfBirth;
	private Date dateOfRegistration;
	private String abhyasiId;
	private Boolean status;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String country;
	private String occupation;
	private String remarks;
	private String idCardNum;
	private String language;
	private String syncStatus;
	private Boolean introduced;
	private Date introducedDate;
	private String introducedRawDate;
	private String introducedBy;

	public SeekerAims() {
	}

	public SeekerAims(int seekerId, Program program) {
		this.seekerId = seekerId;
		this.program = program;
	}

	public SeekerAims(String firstName, String lastName, String middleName, String email,
			String phoneMobile, Integer gender, Date dateOfBirth, Date dateOfRegistration, String abhyasiId,
			Boolean status, String addressLine1, String addressLine2, String city, String state, String country,
			String occupation, String remarks, String idCardNum, String language, String syncStatus, Boolean introduced,
			Date introducedDate, String introducedBy) {
		
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.email = email;
		this.phoneMobile = phoneMobile;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.dateOfRegistration = dateOfRegistration;
		this.abhyasiId = abhyasiId;
		this.status = status;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.occupation = occupation;
		this.remarks = remarks;
		this.idCardNum = idCardNum;
		this.language = language;
		this.syncStatus = syncStatus;
		this.introduced = introduced;
		this.introducedDate = introducedDate;
		this.introducedBy = introducedBy;
	}

	@Id
	@GenericGenerator(name="icn" , strategy="increment")
	@GeneratedValue(generator="icn")
	@Column(name="seeker_ID")
	public int getSeekerId() {
		return this.seekerId;
	}

	public void setSeekerId(int seekerId) {
		this.seekerId = seekerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Program_id", nullable = false)
	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	@Column(name = "First_Name")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "Last_Name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Middle_Name")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone_Mobile")
	public String getPhoneMobile() {
		return this.phoneMobile;
	}

	public void setPhoneMobile(String phoneMobile) {
		this.phoneMobile = phoneMobile;
	}

	@Column(name = "Gender")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_of_Birth")
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_of_Registration")
	public Date getDateOfRegistration() {
		return this.dateOfRegistration;
	}

	public void setDateOfRegistration(Date dateOfRegistration) {
		this.dateOfRegistration = dateOfRegistration;
	}

	@Column(name = "Abhyasi_ID")
	public String getAbhyasiId() {
		return this.abhyasiId;
	}

	public void setAbhyasiId(String abhyasiId) {
		this.abhyasiId = abhyasiId;
	}

	@Column(name = "Status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "Address_Line_1")
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "Address_Line_2")
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "City")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "Occupation")
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "ID_Card_Num")
	public String getIdCardNum() {
		return this.idCardNum;
	}

	public void setIdCardNum(String idCardNum) {
		this.idCardNum = idCardNum;
	}

	@Column(name = "Language")
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "Sync_Status")
	public String getSyncStatus() {
		return this.syncStatus;
	}

	public void setSyncStatus(String syncStatus) {
		this.syncStatus = syncStatus;
	}

	@Column(name = "Introduced")
	public Boolean getIntroduced() {
		return this.introduced;
	}

	public void setIntroduced(Boolean introduced) {
		this.introduced = introduced;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Introduced_Date")
	public Date getIntroducedDate() {
		return this.introducedDate;
	}

	public void setIntroducedDate(Date introducedDate) {
		this.introducedDate = introducedDate;
	}

	@Column(name = "Introduced_By")
	public String getIntroducedBy() {
		return this.introducedBy;
	}

	public void setIntroducedBy(String introducedBy) {
		this.introducedBy = introducedBy;
	}

	/**
	 * @return the introducedRawDate
	 */
	@Column(name = "Introduced_raw_date")
	public String getIntroducedRawDate() {
		return introducedRawDate;
	}

	/**
	 * @param introducedRawDate the introducedRawDate to set
	 */
	public void setIntroducedRawDate(String introducedRawDate) {
		this.introducedRawDate = introducedRawDate;
	}
	
	

}
